const ShopActionTypes = {
  FECTH_COLLECTIONS_START: 'FECTH_COLLECTIONS_START',
  FECTH_COLLECTIONS_SUCCESS: 'FECTH_COLLECTIONS_SUCCESS',
  FECTH_COLLECTIONS_FAIL: 'FECTH_COLLECTIONS_FAIL'
};

export default ShopActionTypes;
